### ISSUE TITLE
LINUX版有吗？

### ISSUE THREAD

**Issue by yang9w** [xuchao1213/AliyunDdnsCSharp#29]
LINUX版有吗？

**Comment by netoyou** [comment]
有的&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xuchao1213/AliyunDdnsCSharp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月23日(星期六) 晚上10:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xuchao1213/AliyunDdnsCSharp] LINUX版有吗？ (Issue #29)





 
LINUX版有吗？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yang9w** [comment]
> 有的&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "xuchao1213/AliyunDdnsCSharp" ***@***.***&gt;; 发送时间:&nbsp;2021年10月23日(星期六) 晚上10:11 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[xuchao1213/AliyunDdnsCSharp] LINUX版有吗？ (Issue #29) LINUX版有吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

没找到Linux的在哪里啊？只找到了Windows的

**Comment by xuchao1213** [comment]
> > 有的 
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "xuchao1213/AliyunDdnsCSharp" _**@**_._**>; 发送时间: 2021年10月23日(星期六) 晚上10:11 _**@**_.**_>; _**@**_.***>; 主题: [xuchao1213/AliyunDdnsCSharp] LINUX版有吗？ (Issue #29) LINUX版有吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> 没找到Linux的在哪里啊？只找到了Windows的

本程序依赖于.netframework4 ,所以暂时不支持linux
